version: "3.7"
services:
  db:
    image: postgres
    container_name: postgresql_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=levartech
      - POSTGRES_USER=levartech
      - POSTGRES_PASSWORD=12345
    volumes:
      # - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    networks:
      - levartech

  redis:
    image: redis
    container_name: redis_data
    ports:
      - "6379:6379"
    networks:
      - levartech

  nginx:
    image: nginx
    container_name: web_server
    # restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - levartech
    depends_on:
      - php
      
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: php_levartech
    container_name: php_engine
    volumes:
      - ./:/var/www/html
    networks:
      - levartech
    environment:
      CONTAINER_ROLE: app

  queue:
    image: php_levartech
    container_name: queue
    depends_on:
      - php
    volumes:
      - ./:/var/www/html
    environment:
      CONTAINER_ROLE: queue
    networks:
      - levartech

networks:
  levartech:
    driver: bridge